<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\ExpenseTracker.Domain\ExpenseTracker.Domain.csproj" />
    <ProjectReference Include="..\..\ExpenseTracker.Application\ExpenseTracker.Application.csproj" />
    <ProjectReference Include="..\..\ExpenseTracker.API\ExpenseTracker.API.csproj" />
  </ItemGroup>
</Project>
