@ExpenseTracker_HostAddress = http://localhost:5149
@Token = <jwt from POST /User/Login>

POST {{ExpenseTracker_HostAddress}}/Expense
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "name": "Coffee",
  "value": 10.50,
  "expenseDate": "2026-03-01T00:00:00"
}

###
